In [0]:
import pandas as pd
import numpy as np
from sklearn import metrics
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split

In [0]:
df=pd.read_csv("/content/sample_data/datasets.csv")

In [4]:
df=df.fillna(0)
df

SEMESTER  AGE  GENDER  ...  STUDY TIME  STUDENT JOB  AVG GPA
0            10   18       0  ...           4            0     4.00
1            10   18       1  ...           3            1     4.00
2             5   23       1  ...           2            1     1.67
3             5   20       1  ...           3            0     3.67
4             6   23       0  ...           5            0     3.33
...         ...  ...     ...  ...         ...          ...      ...
30256        10   24       0  ...           4            1     2.33
30257         1   21       0  ...           4            0     2.00
30258         9   22       0  ...           3            1     2.33
30259         5   21       0  ...           2            1     2.33
30260         6   20       1  ...           4            1     2.67

[30261 rows x 19 columns]

In [0]:
x=df.drop(['AVG GPA'], axis = 1)
y=df['AVG GPA']

In [0]:
#Recursive Feature Elimination
x=df[['SEMESTER','AGE','ADDRESS','FAMILY SIZE','HEALTH','FAMILY SUPPORT','STUDY TIME','NO OF WITHDRAWL']]

In [0]:
#Chi-Squared
x=df[['SEMESTER','ADDRESS','FAMILY SIZE','HEALTH','FAMILY SUPPORT','STUDY TIME','NO OF WITHDRAWL']]

In [0]:
#Pearson Correlation
x=df[['SEMESTER','AGE','ADDRESS','FAMILY SIZE','FAMILY SUPPORT','STUDY TIME','NO OF WITHDRAWL']]

In [0]:
#lasso: SelectFromModel l2
x=df[['AGE','FAMILY SIZE','FAMILY SUPPORT','STUDY TIME','NO OF WITHDRAWL']]

In [0]:
#tree-based: SelectFromModel
x=df[['SEMESTER','AGE','INTERNET','FREETIME','HEALTH','NO OF ABSENCE','NO OF WITHDRAWL','CURRENT CGPA']]

In [0]:
#lightGBM
x=df[['SEMESTER','AGE','TRAVEL TIME','INTERNET','HEALTH','NO OF ABSENCE','NO OF WITHDRAWL','CURRENT CGPA']]

In [0]:
myData=[[8.0,22.0,2.0,3.0,2.0,3.0,0.0,3.2]]

# Linear Regression

In [8]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2,random_state=30)
linear_model = LinearRegression()
model = linear_model.fit(x_train, y_train)
predictions = linear_model.predict(x_test)
accuracy_scale = metrics.r2_score(y_test, predictions)
print('Accuracy Scale (0 - 4): {}'.format(accuracy_scale))

Accuracy Scale (0 - 4): 0.00030306554524039964


In [9]:
predictions = linear_model.predict(myData)
predictions

array([2.73056464])

# K Nearest Neighbors

In [10]:
knn = KNeighborsRegressor(n_neighbors=16)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=30)
knn.fit(x_train, y_train)
pred = knn.predict(x_test)
acc = metrics.r2_score(y_test, pred)
print("Accuracy: {}".format(acc))

ERROR! Session/line number was not unique in database. History logging moved to new session 61
Accuracy: -0.0671914788023733


In [11]:
predictions = knn.predict(myData)
predictions

array([2.436875])

# ADA Boost

In [12]:
adaBoost = AdaBoostRegressor(n_estimators=50, learning_rate=1)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=30)
adaBoost.fit(x_train, y_train)
pred=adaBoost.predict(x_test)
accuracy = metrics.r2_score(y_test, pred)
print('Accuracy: {}'.format(accuracy))

Accuracy: -0.0008769807991924061


In [0]:
predictions = adaBoost.predict(myData)
predictions

array([2.7908316])

# Neural Networks

In [0]:
X = df.iloc[:,:18].values
y = df.iloc[:,18:19].values

In [0]:
#Normalizing the data
sc = StandardScaler()
X = sc.fit_transform(X)

In [0]:
ohe = OneHotEncoder()
y = ohe.fit_transform(y).toarray()

/home/tamjeed/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [0]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3)

In [1]:
from keras.models import Sequential
from keras.layers import Dense

model = Sequential()
model.add(Dense(32, input_dim=18, activation='relu'))
model.add(Dense(28, activation='relu'))
model.add(Dense(23, activation='relu'))
model.add(Dense(19, activation='relu'))
model.add(Dense(15, activation='relu'))
model.add(Dense(11, activation='softmax'))

RuntimeError: ignored

In [0]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [0]:
history = model.fit(X_train, y_train, epochs=100, batch_size=128)

Instructions for updating:
Use tf.cast instead.
Epoch 1/100
21182/21182 [==============================] - 3s 147us/step - loss: 1.3271 - acc: 0.3507
Epoch 2/100
21182/21182 [==============================] - 2s 71us/step - loss: 1.2786 - acc: 0.3762
Epoch 3/100
21182/21182 [==============================] - 2s 83us/step - loss: 1.2764 - acc: 0.3757
Epoch 4/100
21182/21182 [==============================] - 2s 91us/step - loss: 1.2754 - acc: 0.3760
Epoch 5/100
21182/21182 [==============================] - 1s 67us/step - loss: 1.2747 - acc: 0.3769
Epoch 6/100
21182/21182 [==============================] - 1s 65us/step - loss: 1.2742 - acc: 0.3763
Epoch 7/100
21182/21182 [==============================] - 1s 63us/step - loss: 1.2733 - acc: 0.3769
Epoch 8/100
21182/21182 [==============================] - 2s 71us/step - loss: 1.2722 - acc: 0.3765
Epoch 9/100
21182/21182 [==============================] - 1s 67us/step - loss: 1.2712 - acc: 0.3783
Epoch 10/100
21182/21182 [================

21182/21182 [==============================] - 2s 80us/step - loss: 1.2033 - acc: 0.4129
Epoch 79/100
21182/21182 [==============================] - 1s 66us/step - loss: 1.2035 - acc: 0.4154
Epoch 80/100
21182/21182 [==============================] - 1s 67us/step - loss: 1.2026 - acc: 0.4148
Epoch 81/100
21182/21182 [==============================] - 1s 58us/step - loss: 1.2022 - acc: 0.4157
Epoch 82/100
21182/21182 [==============================] - 1s 67us/step - loss: 1.2011 - acc: 0.4179
Epoch 83/100
21182/21182 [==============================] - 1s 67us/step - loss: 1.2022 - acc: 0.4137
Epoch 84/100
21182/21182 [==============================] - 1s 64us/step - loss: 1.2007 - acc: 0.4155
Epoch 85/100
21182/21182 [==============================] - 2s 95us/step - loss: 1.1993 - acc: 0.4167
Epoch 86/100
21182/21182 [==============================] - 2s 95us/step - loss: 1.1989 - acc: 0.4159
Epoch 87/100
21182/21182 [==============================] - 2s 102us/step - loss: 1.1994 - acc: